name = "Lazily Optimized"
author = "Lovinoes"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "539fa4df7800fea9e7b07401fef6b4904f701286527c1f7d4075fbd872578823"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = []
