name = "Lazily Optimized"
author = "Lovinoes"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aad4a68d1923edd7f56771c8db86652c913146ce07b3e21ceb5ca1ac9c3914e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3"]
